### ISSUE TITLE
Fix libzstd-jni integration

### ISSUE THREAD

**Issue by wcygan** [wcygan/spark-minio-k8s#1]
### Expected State

We should be able to run [App.scala](https://github.com/wcygan/spark-minio-k8s/blob/6e0284a2c53bde6175a45877728b22277f3404de/spark-application/src/main/scala/org/example/App.scala) in [wcygan/spark-minio-k8s-spark-application](https://hub.docker.com/r/wcygan/spark-minio-k8s-spark-application) and have it successfully print out a response.

### Actual State

[wcygan/spark-minio-k8s-spark-application](https://hub.docker.com/r/wcygan/spark-minio-k8s-spark-application) is failing with an exception regarding compression and cannot complete successfully

## Exception

Something is wrong with https://github.com/luben/zstd-jni in the Docker image which runs the Spark application

```
failed to map segment from shared object
no zstd-jni-1.5.5-4 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib, /usr/lib64, /lib64]
Unsupported OS/arch, cannot find /linux/aarch64/libzstd-jni-1.5.5-4.so or load zstd-jni-1.5.5-4 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.5-4 in your system.
```

<details>
  <summary>Stacktrace</summary>
  
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.apache.spark.io.CompressionCodec$.createCodec(CompressionCodec.scala:88)
        at org.apache.spark.MapOutputTracker$.serializeOutputStatuses(MapOutputTracker.scala:1526)
        at org.apache.spark.ShuffleStatus.$anonfun$serializedMapStatus$2(MapOutputTracker.scala:358)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.ShuffleStatus.withWriteLock(MapOutputTracker.scala:79)
        at org.apache.spark.ShuffleStatus.serializedMapStatus(MapOutputTracker.scala:355)
        at org.apache.spark.MapOutputTrackerMaster$MessageLoop.handleStatusMessage(MapOutputTracker.scala:751)
        at org.apache.spark.MapOutputTrackerMaster$MessageLoop.run(MapOutputTracker.scala:768)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: /tmp/libzstd-jni-1.5.5-45254816427497626429.so: /tmp/libzstd-jni-1.5.5-45254816427497626429.so: failed to map segment from shared object
no zstd-jni-1.5.5-4 in java.library.path: [/usr/java/packages/lib, /lib, /usr/lib, /usr/lib64, /lib64]
Unsupported OS/arch, cannot find /linux/aarch64/libzstd-jni-1.5.5-4.so or load zstd-jni-1.5.5-4 from system libraries. Please try building from source the jar or providing libzstd-jni-1.5.5-4 in your system.
        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.base/java.lang.System.loadLibrary(Unknown Source)
        at com.github.luben.zstd.util.Native$1.run(Native.java:69)
        at com.github.luben.zstd.util.Native$1.run(Native.java:67)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at com.github.luben.zstd.util.Native.loadLibrary(Native.java:67)
        at com.github.luben.zstd.util.Native.load(Native.java:154)
        at com.github.luben.zstd.util.Native.load(Native.java:85)
        at com.github.luben.zstd.ZstdOutputStreamNoFinalizer.<clinit>(ZstdOutputStreamNoFinalizer.java:18)
        at com.github.luben.zstd.RecyclingBufferPool.<clinit>(RecyclingBufferPool.java:18)
        at org.apache.spark.io.ZStdCompressionCodec.<init>(CompressionCodec.scala:228)
        ... 15 more
```

</details>

## Steps to reproduce

Checkout the faulty version of the application

```
# Clone the repository
git clone https://github.com/wcygan/spark-minio-k8s.git

# Navigate into the cloned directory
cd spark-minio-k8s

# Checkout the specific commit
git checkout 6e0284a2c53bde6175a45877728b22277f3404de
```

Deploy the application

```
skaffold run
```

View the logs

```
kubectl logs spark-minio-k8s-driver -n spark-operator
```

**Comment by wcygan** [comment]
ChatGPT is suggesting a workaround to disable compression:

```java
val spark = SparkSession.builder()
  .appName("YourSparkApp")
  .config("spark.io.compression.codec", "none") // Disable compression
  .getOrCreate()
```

This doesn't look ideal, but we can use it if needed

**Comment by wcygan** [comment]
Alternatively, we can try to modify the docker image to include this in the runtime:

```
RUN apt-get update && apt-get install -y libzstd-jni
```

**Comment by wcygan** [comment]
Fixed on latest commit - https://github.com/wcygan/spark-minio-k8s/commit/908a2df3ff08d8c7ea4bb80686dd76b3db990154

I switched from `openlake/spark-operator @ 3.3.1` (which was suggested on [Spark, MinIO and Kubernetes](https://blog.min.io/spark-minio-kubernetes/)) to [spark-operator @ latest](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator) (which currently uses 3.0.0)

The helm installtion for this is similar to

```
$ helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
$ helm install my-release spark-operator/spark-operator --namespace spark-operator --create-namespace
```
